apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 568026219006.dkr.ecr.eu-central-1.amazonaws.com/demo-frontend
  newName: 568026219006.dkr.ecr.eu-central-1.amazonaws.com/demo-frontend
  newTag: 957903f7
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
